# 应用配置文件
app:
  name: "Go API Scaffold"
  version: "1.0.0"
  env: "development"
  debug: true

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 60s

# 数据库配置
database:
  driver: "sqlite"  # sqlite, postgres, mysql
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  dbname: "go_api_scaffold"
  sslmode: "disable"
  timezone: "UTC"
  
  # SQLite 配置
  sqlite:
    path: "./data/app.db"
  
  # 连接池配置
  pool:
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300s
    conn_max_idle_time: 60s

# Redis 配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# 日志配置
log:
  level: "info"  # trace, debug, info, warn, error, fatal, panic
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file_path: "./logs/app.log"
  max_size: 100  # MB
  max_backups: 3
  max_age: 28  # days
  compress: true

# JWT 配置
jwt:
  secret: "your-secret-key-change-in-production"
  expires_in: 24h
  refresh_expires_in: 168h  # 7 days

# CORS 配置
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  exposed_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 12h

# 限流配置
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst: 10

# 文件上传配置
upload:
  max_size: 10485760  # 10MB
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
  upload_path: "./uploads"

# 邮件配置
mail:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from_name: "Go API Scaffold"
  from_email: "noreply@example.com"

# 缓存配置
cache:
  default_expiration: 10m
  cleanup_interval: 5m

# 监控配置
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"
  
# 安全配置
security:
  bcrypt_cost: 12
  session_timeout: 30m
  max_login_attempts: 5
  lockout_duration: 15m

# 第三方服务配置
services:
  # 示例：外部 API
  external_api:
    base_url: "https://api.example.com"
    api_key: "your-api-key"
    timeout: 30s
    retry_count: 3

# 开发环境特定配置
development:
  auto_migrate: true
  seed_data: true
  profiler_enabled: true

# 生产环境特定配置
production:
  auto_migrate: false
  seed_data: false
  profiler_enabled: false
  
# 测试环境特定配置
test:
  database:
    driver: "sqlite"
    sqlite:
      path: ":memory:"
  log:
    level: "error"