# 应用配置文件
app:
  name: "go-api-scaffold"
  version: "1.0.0"
  environment: "development"

# 服务器配置
server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# 数据库配置
database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "147896325a"
  database: "go_admin"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"