# Go API Scaffold 配置文件

app:
  name: "go-api-scaffold"
  version: "1.0.0"
  environment: "development"

server:
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: ""
  database: "go_api_scaffold"
  ssl_mode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

log:
  level: "info"
  format: "json"
  output: "stdout"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0